void bootanimation(){
  lcd.print("P");
  delay(100);
  lcd.print("r");
  delay(100);
  lcd.print("o");
  delay(100);
  lcd.print("j");
  delay(100);
  lcd.print("e");
  delay(100);
  lcd.print("c");
  delay(100);
  lcd.print("t");
  delay(100);
  lcd.setCursor(0,1);
  lcd.print("F");
  delay(100);
  lcd.print("i");
  delay(100);
  lcd.print("t");
  delay(100);
  lcd.print("z");
  delay(100);
  lcd.print("g");
  delay(100);
  lcd.print("e");
  delay(100);
  lcd.print("r");
  delay(100);
  lcd.print("a");
  delay(100);
  lcd.print("l");
  delay(100);
  lcd.print("d");

  
  delay(500);
  lcd.setCursor(11, 1);
  lcd.print("EX");
  delay(500);
  lcd.setCursor(11,1);
  lcd.print("  ");
  delay(500);
  lcd.setCursor(11, 1);
  lcd.print("EX");
  delay(500);
  lcd.setCursor(11,1);
  lcd.print("  ");
  delay(500);
  lcd.setCursor(11, 1);
  lcd.print("EX");
  delay(500);
  lcd.setCursor(11,1);
  lcd.print("  ");
  delay(500);
  lcd.setCursor(11, 1);
  lcd.print("EX");
  delay(3000);
  lcd.setCursor(12,1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(11,1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(9, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(8, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(7, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(6, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(5, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(4, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(3, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(2, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(1, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(0, 1);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(6, 0);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(5, 0);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(4, 0);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(3, 0);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(2, 0);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(1, 0);
  lcd.print(" ");
  delay(100);
  lcd.setCursor(0, 0);
  lcd.print(" ");
  delay(100);
}
